#!/usr/bin/env python3
"""Build the single-file Colab notebooks from the Jupytext sources.

The Colab bundles used to be hand-edited copies that drifted from
`notebooks/`. Now they are generated: `lab22/*.py` is written with
`%%writefile`, then every notebook's cells follow in order.

    python scripts/build_colab.py          # rewrite colab/*.ipynb
    python scripts/build_colab.py --check  # exit 1 if they are stale
"""
from __future__ import annotations

import argparse
import base64
import gzip
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
WORKDIR = "/content/lab22"
STAGES = [
    ("00_dpo_loss_from_scratch", "core · CPU"),
    ("01_sft_mini", "core"),
    ("02_preference_data", "core"),
    ("03_dpo_train", "core"),
    ("04_compare_and_eval", "core"),
    ("03b_dpo_variants", "bonus"),
    ("05_merge_deploy_gguf", "bonus"),
    ("06_benchmark", "bonus"),
    ("07_grpo_bonus", "bonus"),
]
TARGETS = {"T4": "Lab22_DPO_T4.ipynb", "BIGGPU": "Lab22_DPO_BigGPU.ipynb"}
CELL = re.compile(r"^# %%(?P<md> \[markdown\])?.*$", re.MULTILINE)


def requirements() -> list[str]:
    """Requirement specs from requirements.txt, minus test/notebook tooling."""
    skip = ("jupyterlab", "jupytext", "pytest")
    specs = []
    for line in (REPO / "requirements.txt").read_text(encoding="utf-8").splitlines():
        spec = line.split("#", 1)[0].strip()
        if spec and not spec.startswith(skip):
            specs.append(spec)
    return specs


def source_lines(text: str) -> list[str]:
    lines = text.splitlines(keepends=True)
    if lines:
        lines[-1] = lines[-1].rstrip("\n")
    return lines


def md(text: str) -> dict:
    return {"cell_type": "markdown", "metadata": {}, "source": source_lines(text)}


def code(text: str) -> dict:
    return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": source_lines(text)}


def percent_cells(path: Path) -> list[dict]:
    """Parse a Jupytext py:percent file (header block dropped)."""
    text = path.read_text(encoding="utf-8")
    marks = list(CELL.finditer(text))
    cells = []
    for i, m in enumerate(marks):
        end = marks[i + 1].start() if i + 1 < len(marks) else len(text)
        body = text[m.end() :end].strip("\n")
        if not body.strip():
            continue
        if m.group("md"):
            body = "\n".join(line[2:] if line.startswith("# ") else line.lstrip("#") for line in body.splitlines())
            cells.append(md(body))
        else:
            cells.append(code(body))
    return cells


RELEASE_GPU = (
    "# Free GPU memory held by the previous stage (model, trainer, llama.cpp handle).\n"
    "import gc\n"
    "for _name in ('trainer', 'model', 'ref_model', 'llm', 'policy', 'ref', 'tokenizer'):\n"
    "    globals().pop(_name, None)\n"
    "gc.collect()\n"
    "try:\n"
    "    import torch\n"
    "    if torch.cuda.is_available():\n"
    "        torch.cuda.empty_cache()\n"
    "        print(f'GPU memory in use: {torch.cuda.memory_allocated() / 1e9:.2f} GB')\n"
    "except ImportError:\n"
    "    pass"
)


def render_expanded(tier: str) -> dict:
    big = tier == "BIGGPU"
    pins = " ".join(f'"{s}"' for s in requirements())
    cells = [
        md(
            f"# Lab 22 — DPO/ORPO Alignment ({'BigGPU' if big else 'T4'} tier)\n\n"
            "**Track 3 · Day 22 · VinUni AICB.** Generated by `scripts/build_colab.py` from "
            "`notebooks/*.py` and `lab22/*.py`; do not edit by hand.\n\n"
            "Core: NB0 → NB4. Bonus: NB3b (variants), NB5 (GGUF), NB6 (lm-eval), NB7 (GRPO).\n"
            "Each stage reloads what it needs from disk, so after a crash you can restart the "
            "runtime, rerun section A, and continue from the stage that failed."
        ),
        md("## A. Setup"),
        code(
            "import os\n"
            f'os.environ["COMPUTE_TIER"] = "{tier}"\n'
            "# NB4 judges automatically with a panel of two local reward models (no key needed).\n"
            "# Optional API judge as a cross-check (two A/B orders):\n"
            '# os.environ["JUDGE_PROVIDER"] = "gemini"   # or "openai" / "anthropic"\n'
            '# os.environ["JUDGE_MODEL"] = "<current model id>"\n'
            '# from google.colab import userdata; os.environ["GEMINI_API_KEY"] = userdata.get("GEMINI_API_KEY")\n'
            "# Put API keys in Colab secrets, never in the notebook."
        ),
        code(f"!pip install -q {pins}" + (' "vllm>=0.10"' if big else "")),
        code(
            "from pathlib import Path\n"
            f'WORK = Path("{WORKDIR}")\n'
            '(WORK / "lab22").mkdir(parents=True, exist_ok=True)\n'
            "os.chdir(WORK)\n"
            "print(Path.cwd())"
        ),
        md("### Helper package `lab22/` (same files as the repo)"),
    ]
    for module in sorted((REPO / "lab22").glob("*.py")):
        body = module.read_text(encoding="utf-8")
        cells.append(code(f"%%writefile {WORKDIR}/lab22/{module.name}\n{body}"))
    for i, (stem, kind) in enumerate(STAGES):
        if i:
            # One Colab kernel runs every stage, so drop the previous stage's GPU objects.
            cells.append(code(RELEASE_GPU))
        cells.append(md(f"---\n# ⏵ `notebooks/{stem}.py` ({kind})"))
        cells.extend(percent_cells(REPO / "notebooks" / f"{stem}.py"))
    return {
        "cells": cells,
        "metadata": {
            "accelerator": "GPU",
            "colab": {"gpuType": "A100" if big else "T4", "provenance": []},
            "kernelspec": {"display_name": "Python 3", "name": "python3"},
            "language_info": {"name": "python"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }


def ready_payload() -> str:
    files = {}
    for folder in ('lab22', 'scripts', 'notebooks', 'submission', 'docs'):
        for path in sorted((REPO / folder).rglob('*')):
            if path.suffix in ('.py', '.md') and '__pycache__' not in path.parts:
                # Bundle the original reflection template, never a student's generated report.
                if folder == 'submission' and path.name not in ('REFLECTION.md', 'README.md'):
                    continue
                if path.name == 'REFLECTION.md' and '<Họ Tên>' not in path.read_text(encoding='utf-8'):
                    continue
                files[path.relative_to(REPO).as_posix()] = path.read_text(encoding='utf-8')
    for name in ('requirements.txt', 'requirements-biggpu.txt', 'README.md', 'rubric.md', 'Makefile', '.gitignore', 'LICENSE', 'HARDWARE-GUIDE.md', 'BONUS-CHALLENGE.md', 'COLAB-RUN.md'):
        if (REPO / name).exists():
            files[name] = (REPO / name).read_text(encoding='utf-8')
    return base64.b64encode(gzip.compress(json.dumps(files, ensure_ascii=False, sort_keys=True).encode(), mtime=0)).decode()


def render_ready() -> dict:
    pins = [s for s in requirements() if not s.startswith(('llama-cpp-python', 'lm-eval'))]
    cells = [
        md('# Lab 22 — Phạm Hoàng Trọng · bản chạy và đóng gói tự động\n\n'
           'Chọn **Runtime → Change runtime type → T4 GPU**, rồi **Run all**. '
           'NB0–NB4 chạy trước; sau đó thử bonus miễn phí. Mỗi phần có notebook riêng giữ output. '
           'Chưa chạy GPU thì chưa có số liệu hay điểm bonus.\n\n'
           'Mặc định lưu vào Google Drive để giữ mô hình khi Colab mất phiên. Cho phép kết nối Drive khi được hỏi. '
           'Toàn bộ bonus mất nhiều giờ và có thể vượt hạn mức T4 miễn phí. '
           'Nếu bị ngắt, mở phiên GPU mới và Run all; các phần đã thành công được bỏ qua khi cấu hình không đổi. '
           'Không bảo đảm tiếp tục giữa một lượt huấn luyện chưa hoàn thành.\n\n'
           'Cuối mỗi phần, `Lab22_submission.zip` được cập nhật. Đọc lại phản tư tự sinh trước khi nộp; '
           'ảnh GGUF vẫn cần chụp màn hình cell theo yêu cầu rubric.'),
        code('STUDENT_NAME = "Phạm Hoàng Trọng"\n'
             'STUDENT_COHORT = "A20-K4 · 2A202602765"\n'
             'USE_DRIVE = True\n'
             'DRIVE_FOLDER = "Lab22_PhamHoangTrong_2A202602765"\n'
             'COMPUTE_TIER = "T4"\n'
             '# Giữ đủ dữ liệu bắt buộc; không giảm xuống cấu hình chạy thử.\n'
             'BONUSES = "variants,gguf,benchmark,grpo,beta"\n'
             '# Chạy riêng phần lỗi: ONLY="gguf", "variants", "benchmark", "grpo", "beta".\n'
             '# ONLY="core" chỉ chạy bắt buộc; ONLY="finish" chỉ tạo báo cáo + zip.\n'
             'ONLY = ""\n'
             'RESUME = True\n'
             '# Tuỳ chọn cần tài khoản/key: để trống thì không gọi dịch vụ.\n'
             'CROSS_JUDGE_PROVIDER = ""  # gemini / openai / anthropic\n'
             'CROSS_JUDGE_MODEL = ""     # model ID do bạn chọn\n'
             'HF_REPO_ID = ""           # tài-khoản/lab22-dpo-experimental\n'),
        code('import os, sys, json, gzip, base64, subprocess\n'
             'from pathlib import Path\n'
             'if USE_DRIVE:\n'
             '    from google.colab import drive\n'
             '    drive.mount("/content/drive")\n'
             '    WORK = Path("/content/drive/MyDrive") / DRIVE_FOLDER\n'
             'else:\n'
             '    WORK = Path("/content/lab22")\n'
             'WORK.mkdir(parents=True, exist_ok=True)\n'
             f'payload = json.loads(gzip.decompress(base64.b64decode("{ready_payload()}")))\n'
             'for relative, contents in payload.items():\n'
             '    path = WORK / relative\n'
             '    if relative == "submission/REFLECTION.md" and path.exists():\n'
             '        continue\n'
             '    path.parent.mkdir(parents=True, exist_ok=True)\n'
             '    path.write_text(contents, encoding="utf-8")\n'
             'os.chdir(WORK)\n'
             'os.environ.update(COMPUTE_TIER=COMPUTE_TIER, STUDENT_NAME=STUDENT_NAME, STUDENT_COHORT=STUDENT_COHORT, GEN_BATCH_SIZE="2", JUDGE_PROVIDER="rm")\n'
             '# OOM: thêm os.environ["MAX_LEN"]="512" rồi chạy lại core; cấu hình đổi sẽ huấn luyện lại.\n'
             'print("Thư mục làm việc:", WORK)\n'),
        code(f'subprocess.run([sys.executable, "-m", "pip", "install", "-q", *{pins!r}, "nbclient>=0.10,<1", "nbformat>=5.10,<6", "ipykernel>=6,<8"], check=True)\n'
             'subprocess.run([sys.executable, "scripts/build_colab.py"], check=True)\n'
             '# Kiểm tra GPU trong tiến trình riêng để không nạp transformers trước Unsloth.\n'
             'subprocess.run([sys.executable, "-c", "import torch; assert torch.cuda.is_available(), \'Hãy chọn T4 GPU\'; print(torch.cuda.get_device_name(0))"], check=True)'),
        code('from google.colab import userdata\n'
             'if CROSS_JUDGE_PROVIDER and CROSS_JUDGE_MODEL:\n'
             '    key_name = {"gemini":"GEMINI_API_KEY", "openai":"OPENAI_API_KEY", "anthropic":"ANTHROPIC_API_KEY"}[CROSS_JUDGE_PROVIDER]\n'
             '    os.environ[key_name] = userdata.get(key_name)\n'
             '    os.environ.update(CROSS_JUDGE_PROVIDER=CROSS_JUDGE_PROVIDER, CROSS_JUDGE_MODEL=CROSS_JUDGE_MODEL)\n'
             '    BONUSES += ",cross"\n'
             'if HF_REPO_ID:\n'
             '    os.environ["HF_TOKEN"] = userdata.get("HF_TOKEN")\n'
             '    os.environ["HF_REPO_ID"] = HF_REPO_ID\n'
             '    BONUSES += ",hub"\n'
             'command = [sys.executable, "-u", "scripts/run_colab.py", "--bonuses", BONUSES]\n'
             'if RESUME: command.append("--resume")\n'
             'if ONLY: command += ["--only", ONLY]\n'
             'result = subprocess.run(command)\n'
             'print("Pipeline exit code:", result.returncode)\n'
             'print("Đọc data/eval/run_status.json để biết phần nào đã thành công hoặc còn lỗi.")'),
        md('## Kết quả và tải bài nộp\n\n'
           'Zip chứa các notebook đã chạy với output, ảnh, JSON, dữ liệu preference, mã nguồn và phản tư. '
           'Không chứa trọng số hay khóa API. Giữ mô hình trong Drive nếu muốn chạy tiếp bonus. '
           'Nếu runtime bị ngắt, lấy zip trong thư mục Drive ngay cả khi chưa tới cell này. '
           'Giải nén zip vào repo, đọc/điều chỉnh phản tư theo quan sát thật, commit rồi nộp link GitHub public trên LMS. '
           'Không gọi là hoàn thành bonus nếu `run_status.json` báo lỗi.'),
        code('from IPython.display import display, Markdown, Image\n'
             'report = WORK / "submission/REFLECTION.md"\n'
             'if report.exists(): display(Markdown(report.read_text(encoding="utf-8")))\n'
             'for filename in ("03b-variants.png", "07-benchmark-comparison.png", "08-grpo-reward.png", "bonus-beta-sweep.png"):\n'
             '    image_path = WORK / "submission/screenshots" / filename\n'
             '    if image_path.exists(): display(Image(filename=str(image_path)))\n'
             'meta = WORK / "data/eval/deploy_meta.json"\n'
             'if meta.exists():\n'
             '    info = json.loads(meta.read_text(encoding="utf-8"))\n'
             '    print("GGUF Q4_K_M:", info["gguf_path"])\n'
             '    print(info["smoke_prompt"], "\\nHF:\\n", info["hf_answer"], "\\nGGUF:\\n", info["gguf_answer"])\n'
             '    print("Chụp màn hình phần này và lưu submission/screenshots/06-gguf-smoke.png vào repo.")\n'
             'from google.colab import files\n'
             'archive = WORK / "Lab22_submission.zip"\n'
             'if archive.exists(): files.download(str(archive))\n'
             'else: print("Chưa có zip: kiểm tra lỗi cài đặt hoặc GPU ở các cell trước.")'),
    ]
    return {'cells': cells, 'metadata': {'accelerator': 'GPU', 'colab': {'gpuType': 'T4', 'provenance': []}, 'kernelspec': {'name': 'python3', 'display_name': 'Python 3'}, 'language_info': {'name': 'python'}}, 'nbformat': 4, 'nbformat_minor': 5}


def render(tier: str) -> dict:
    """The standard T4 filename is the complete automatic submission workflow."""
    return render_ready() if tier == 'T4' else render_expanded(tier)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if colab/*.ipynb differ from the sources")
    args = parser.parse_args()
    if not args.check:
        (REPO / "colab").mkdir(parents=True, exist_ok=True)
    stale = []
    for tier, name in TARGETS.items():
        path = REPO / "colab" / name
        nb = render(tier)
        if args.check:
            if not path.exists() or json.loads(path.read_text(encoding="utf-8")) != nb:
                stale.append(name)
            continue
        path.write_text(json.dumps(nb, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
        print(f"wrote colab/{name} ({len(nb['cells'])} cells)")
    ready_path = REPO / 'colab/Lab22_READY_ALL.ipynb'
    ready = render_ready()
    if args.check:
        if not ready_path.exists() or json.loads(ready_path.read_text(encoding='utf-8')) != ready:
            stale.append(ready_path.name)
    else:
        ready_path.write_text(json.dumps(ready, ensure_ascii=False, indent=1) + '\n', encoding='utf-8')
        print(f'wrote colab/{ready_path.name} ({len(ready["cells"])} cells)')
    if stale:
        print(f"stale: {stale}; run `python scripts/build_colab.py`")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
